#!/bin/bash
echo "server {
	listen 80 default_server;
	return 301 https://$1;

	root /var/www/html;

	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		try_files \$uri \$uri/ =404;
	}
}" > /etc/nginx/sites-available/default
cp -r /script/assets /var/www/html/
cp -r /script/images /var/www/html/
mv /script/index.htm /var/www/html
rm /var/www/html/index.nginx-debian.html
systemctl restart nginx
