#!/bin/bash
#add iptables rules
echo "*filter
:INPUT DROP [1000:63936]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [180:18808]
-A INPUT -i lo -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p tcp --tcp-flags ALL NONE -j DROP
-A INPUT -p tcp -m multiport --dport $1,80,443 -m state --state NEW -j ACCEPT
COMMIT
*raw
:PREROUTING ACCEPT [32449:2184091]
:OUTPUT ACCEPT [1060:108594]
COMMIT
*nat
:PREROUTING ACCEPT [30611:1960784]
:INPUT ACCEPT [44:2816]
:OUTPUT ACCEPT [15:1039]
:POSTROUTING ACCEPT [15:1039]
COMMIT" > /etc/iptables/rules.v4
iptables-restore < /etc/iptables/rules.v4
