#!/bin/bash
echo "server {
	listen 80;
	return 301 https://$1;
}" > /etc/nginx/sites-available/default
cp -r /script/assets /var/www/html/
cp -r /script/images /var/www/html/
mv /script/index.htm /var/www/html
rm /var/www/html/index.nginx-debian.html
touch /etc/nginx/conf.d/ssl.conf
echo "server {
	location / {
		deny 127.0.0.1/8;
	}
	listen	443 default_server ssl;

	root	/var/www/html/;
	index	index.htm;

	error_page	497	https://$1;

	ssl                  on;
	ssl_certificate      /etc/ssl/server.crt;
	ssl_certificate_key  /etc/ssl/server.key;
}" > /etc/nginx/conf.d/ssl.conf
echo "user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
	worker_connections 2048;
}

http {
	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;
	include /etc/nginx/mime.types;
	default_type application/octet-stream;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;
	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;
	gzip on;
	gzip_disable "msie6";
	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;
}" > /etc/nginx/nginx.conf
systemctl restart nginx
