#!/bin/bash
#add ssh
echo "port $1\nPermitRootLogin no\nPubkeyAuthentication yes\nPasswordAuthentication no\nHostbasedAuthentication no\nChallengeResponseAuthentication no\nKerberosAuthentication no\nGSSAPIAuthentication no\nUsePAM yes\nX11Forwarding yes\nPrintMotd no\nAcceptEnv LANG LC_*" > /etc/ssh/sshd_config
systemctl restart sshd
