#!/bin/bash
#add iptables rules
echo "*filter\n:INPUT DROP [1000:63936]\n:FORWARD ACCEPT [0:0]\n:OUTPUT ACCEPT [180:18808]\n-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT\n-A INPUT -m state --state NEW -p tcp -m multiport --dport $1, http, https -j ACCEPT\n-A INPUT -i lo -j ACCEPT\nCOMMIT\n*raw\n:PREROUTING ACCEPT [32449:2184091]\n:OUTPUT ACCEPT [1060:108594]\nCOMMIT\n*nat\n:PREROUTING ACCEPT [30611:1960784]\n:INPUT ACCEPT [44:2816]\n:OUTPUT ACCEPT [15:1039]\n:POSTROUTING ACCEPT [15:1039]\nCOMMIT" > /etc/iptables/rules.v4
systemctl restart iptables
